add bsttool_fetch to cover local existence

diff --git a/bash_bst b/bash_bst
--- a/bash_bst
+++ b/bash_bst
@@ -13,7 +13,7 @@ g_cover_flag=1
 g_limit_flag=1
 g_size_limit=1 # MB
 
-# $1: dest path
+# $1: remote path
 #
 # return value
 # 0: user allow and delete existing remote file
@@ -21,12 +21,34 @@ g_size_limit=1 # MB
 bsttool_duplicate_warning()
 {
     local resp
-    echo -n "dest file exist, do you want to cover it? (n/y) "
+    echo -n "remote file exist, do you want to cover it? (n/y) "
     read resp
     case "$resp" in 
         "y"|"Y")
             # remove remote reource first
             bst_tool delete "$1"
+            return 0
+            ;;
+        *)
+            return 1
+            ;;
+    esac
+}
+
+# $1: local path
+#
+# return value
+# 0: user allow and delete existing local file
+# 1: user disallow and do nothing
+bsttool_existence_warning()
+{
+    local resp
+    echo -n "local file exist, do you want to cover it? (n/y) "
+    read resp
+    case "$resp" in 
+        "y"|"Y")
+            # remove local reource first
+            rm "$1"
             return 0
             ;;
         *)
@@ -105,13 +127,13 @@ bsttool_huge_file_warning()
 # 3: dir exist and not empty
 bsttool_query_path()
 {
-    local dst=$1
-    local res=$(bst_tool ls "$dst")
+    local remote=$1
+    local res=$(bst_tool ls "$remote")
     local line=$(echo "$res" | sed -n '2p')
     local str=${line/"total size"//}
     local download="/tmp/bst.tmp"
     local ret=0
-    #echo "dst: $dst, res: $res, line: $line, str: $str"
+    #echo "remote: $remote, res: $res, line: $line, str: $str"
     if [ "$str" != "$line" ]; then 
         # normal return
         ret=$(echo "$line" | awk '{print $NF}')
@@ -128,7 +150,7 @@ bsttool_query_path()
             # you can NOT download a dir.
             echo "dir or file exist, try download to check"
             rm "$download" > /dev/null 2>&1 # otherwise bst_tool will fail
-            line=$(bst_tool get "$dst" "$download" | sed -n '2p')
+            line=$(bst_tool get "$remote" "$download" | sed -n '2p')
             if [ ! -z "$BST_TOOL_VERBOSE" ]; then 
                 echo "download: $line"
             fi
@@ -146,7 +168,7 @@ bsttool_query_path()
     else
         # server response error, no such path
         if [ ! -z "$BST_TOOL_VERBOSE" ]; then 
-            echo "no such path: $dst"
+            echo "no such path: $remote"
         fi
 
         ret=0
@@ -164,30 +186,29 @@ bsttool_query_path()
 bsttool_replace ()
 {
     if [ $# -lt 1 ]; then 
-        echo "Usage: bstput src [dst]"
+        echo "Usage: bstput local [remote]"
         return 1
     fi
 
-    local src=$1
-    local dst="/"
+    local local=$1
+    local remote="/"
     if [ $# -gt 1 ]; then 
-        dst=$2
+        remote=$2
     fi
 
     # first check dest existence
-    local resp
     #local download="/tmp/bst.tmp"
-    local name=${src##*/} # remove path part, want name only
+    local name=${local##*/} # remove path part, want name only
     if [ -z "$name" ]; then 
-        name="$src"
+        name="$local"
     fi
 
-    local path=$dst/$name
+    local path=$remote/$name
     if [ ! -z "$BST_TOOL_VERBOSE" ]; then 
         echo "path=$path"
     fi
 
-    bsttool_query_path "$dst"
+    bsttool_query_path "$remote"
     local res=$?
     case $res in
         0)
@@ -196,7 +217,7 @@ bsttool_replace ()
             ;;
         1)
             # file exist
-            bsttool_duplicate_warning "$dst"
+            bsttool_duplicate_warning "$remote"
             if [ $? -ne 0 ]; then 
                 return 1
             fi
@@ -225,18 +246,66 @@ bsttool_replace ()
             ;;
     esac
 
-    bst_tool put "$src" "$dst"
+    bst_tool put "$local" "$remote"
     return 0
 }
 
+# $1: remote file path
+# $2: local file path (optional)
+bsttool_fetch ()
+{
+    if [ $# -lt 1 ]; then 
+        echo "Usage: bstget remote [local]"
+        return 1
+    fi
+
+    local remote=$1
+    local name=${remote##*/} # remove path part, want name only
+    if [ -z "$name" ]; then 
+        name="$remote"
+    fi
+
+    local local="./"
+    if [ $# -gt 1 ]; then 
+        local=$2
+    fi
+
+    # check dest existence
+    if [ -e "$local" ]; then 
+        if [ -d "$local" ]; then 
+            # for dir, test sub file existence
+            if [ -e "$local/$name" -a ! -d "$local/$name" ]; then 
+                # dest file exist, warning...
+                bsttool_existence_warning "$local/$name"
+                if [ $? -ne 0 ]; then 
+                    return 1
+                fi
+            fi
+        else 
+        #elif [ -f "$local" ]; then
+            # dest file exist, warning...
+            bsttool_existence_warning "$local"
+            if [ $? -ne 0 ]; then 
+                return 1
+            fi
+        fi
+    fi
+
+    if [ ! -z "$BST_TOOL_VERBOSE" ]; then 
+        echo "path=$local"
+    fi
+
+    bst_tool get "$remote" "$local"
+    return 0
+}
 
 # $1: remote path
 # $2: depth
 bsttool_list_recur ()
 {
-    local dst=$1
+    local remote=$1
     local depth=$(($2+1))
-    local res=$(bst_tool ls "$dst")
+    local res=$(bst_tool ls "$remote")
     local line=$(echo "$res" | sed -n '2p')
     local str=${line/"total size"//}
     local ret=0
@@ -254,7 +323,7 @@ bsttool_list_recur ()
     local size="" # has K/M/G postfix
     local type=""
     local name=""
-    echo "$dst [$depth-$ret]:"
+    echo "$remote [$depth-$ret]:"
     for n in $(seq 6 $max)
     do
         # why sed -n "$np" don't work ?
@@ -271,11 +340,11 @@ bsttool_list_recur ()
 
             # do for sub dirs
             local path=""
-            #echo "last char: ${dst:0-1}"
-            if [ ${dst:0-1} == "/" ]; then 
-                path="$dst$name"
+            #echo "last char: ${remote:0-1}"
+            if [ ${remote:0-1} == "/" ]; then 
+                path="$remote$name"
             else
-                path="$dst/$name"
+                path="$remote/$name"
             fi
 
             bsttool_list_recur "$path" $depth
@@ -292,12 +361,12 @@ bsttool_list_recur ()
 # $1: remote path
 bsttool_list_all ()
 {
-    local dst="/"
+    local remote="/"
     if [ $# -gt 0 ]; then 
-        dst=$1
+        remote=$1
     fi
 
-    bsttool_list_recur "$dst" 0 
+    bsttool_list_recur "$remote" 0 
 }
 
 # $1: remote path
@@ -305,11 +374,11 @@ bsttool_list_all ()
 # $3: depth
 bsttool_get_recur ()
 {
-    local src=$1
-    local dst=$2
+    local remote=$1
+    local local=$2
     local depth=$(($3+1))
 
-    local res=$(bst_tool ls "$src")
+    local res=$(bst_tool ls "$remote")
     local line=$(echo "$res" | sed -n '2p')
     local str=${line/"total size"//}
     local ret=0
@@ -329,7 +398,7 @@ bsttool_get_recur ()
     local name=""
     local path=""
     local filesize=0
-    echo "$src [$depth-$ret]:"
+    echo "$remote [$depth-$ret]:"
     for n in $(seq 6 $max)
     do
         # why sed -n "$np" don't work ?
@@ -360,11 +429,11 @@ bsttool_get_recur ()
 
             cd "$name"
             # do for sub dirs
-            #echo "last char: ${src:0-1}"
-            if [ ${src:0-1} == "/" ]; then 
-                path="$src$name"
+            #echo "last char: ${remote:0-1}"
+            if [ ${remote:0-1} == "/" ]; then 
+                path="$remote$name"
             else
-                path="$src/$name"
+                path="$remote/$name"
             fi
 
             bsttool_get_recur "$path" "$name" $depth
@@ -444,10 +513,10 @@ bsttool_get_recur ()
                 fi
             fi
 
-            if [ ${src:0-1} == "/" ]; then 
-                path="$src$name"
+            if [ ${remote:0-1} == "/" ]; then 
+                path="$remote$name"
             else
-                path="$src/$name"
+                path="$remote/$name"
             fi
 
             bst_tool get "$path" "$name"
@@ -462,41 +531,41 @@ bsttool_get_recur ()
 bsttool_get_all ()
 {
     if [ $# -lt 1 ]; then 
-        echo "Usage: bstrget src [dst]"
+        echo "Usage: bstrget remote [local]"
         return 1
     fi
 
-    local src=$1
-    local dst=""
+    local remote=$1
+    local local=""
     local type=0
     g_cover_flag=1 # no once
     local dirold=""
     if [ $# -gt 1 ]; then 
-        dst=$2
+        local=$2
     else
         # get name part
         local tmp=""
-        if [ ${src:0-1} == "/" ]; then 
+        if [ ${remote:0-1} == "/" ]; then 
             # cut tailing '/'
-            tmp="${src:0:$((${#src}-1))}"
+            tmp="${remote:0:$((${#remote}-1))}"
         else
-            tmp="$src"
+            tmp="$remote"
         fi
 
-        dst="${tmp##*/}"
+        local="${tmp##*/}"
     fi
 
-    if [ -z "$dst" -o "$dst" == "/" ]; then 
+    if [ -z "$local" -o "$local" == "/" ]; then 
         # default name
-        dst="setup"
+        local="setup"
     fi
 
-    bsttool_query_path "$src"
+    bsttool_query_path "$remote"
     type=$?
     case $type in
         0)
             # not exist
-            echo "remote src not exist"
+            echo "remote not exist"
             return 1
             ;;
         1)
@@ -510,10 +579,10 @@ bsttool_get_all ()
             ;;
         3)
             # dir exist
-            if [ ! -d "$dst" ]; then 
-                mkdir -p "$dst"
+            if [ ! -d "$local" ]; then 
+                mkdir -p "$local"
                 if [ ! -z "$BST_TOOL_VERBOSE" ]; then 
-                    echo "create download dir $dst"
+                    echo "create download dir $local"
                 fi
             else
                 bsttool_duplicate_dir_warning
@@ -525,7 +594,7 @@ bsttool_get_all ()
             fi
 
             dirold="$PWD"
-            cd "$dst"
+            cd "$local"
             ;;
         *)
             echo "should not reach here !"
@@ -543,7 +612,7 @@ bsttool_get_all ()
         echo "size limit: $g_size_limit"
     fi
 
-    bsttool_get_recur "$src" "$dst" 0
+    bsttool_get_recur "$remote" "$local" 0
     if [ ! -z "$dirold" ]; then 
         cd "$dirold"
     fi
@@ -551,7 +620,7 @@ bsttool_get_all ()
 
 # alias
 alias bstput=bsttool_replace
-alias bstget='bst_tool get'
+alias bstget=bsttool_fetch
 alias bstdel='bst_tool delete'
 alias bstls='bst_tool ls'
 alias bstrls=bsttool_list_all
